### ISSUE TITLE
Add Arcane brilliance to the buff reminder

### ISSUE THREAD

**Issue by Swork91** [ElvUI-Cataclysm/ElvUI_Enhanced-4.3.4#4]
There are a lot more raid buffs in cataclysm counting totems, auras, and passives, but the only real other casted buff is AB. So adding it to the other 6 tracked buffs making it a nice even 7 could be a helpful reminder. 

Also some more options in the reminder options (Buffs and Debuffs>Reminder) To configure tracked buffs and maybe have all buffs as an option?

**Comment by Apollyonn** [comment]
Arcane brilliance is already there, your toon must be a caster in order to show.
![1877bf8c01059bd431b56c98574d7294](https://user-images.githubusercontent.com/19589902/36335958-74f4ab3e-138c-11e8-981e-ad078ed53439.png)

At the moment reminder bar shows only the buffs that benefits your toon. If you are a caster it will show buffs that increase caster stats.
For example it will show the following buffs.

Mark of the Wild
Fortitude
Arcane Brilliance
Blessing of Might

Thats the only buffs that benefits caster stats.

You can't stack Mark of the Wild with Greater Blessing of Kings or Fel Intelligence with Blessing of Might, so i don't really see the point of modifying the reminder bar

**Comment by Swork91** [comment]
Alright I'm probably looking for another addon to track raid buffs better. 

How does it tell if I'm a caster though - Is that when setting up bars or by specialization?

**Comment by Apollyonn** [comment]
By spec

**Comment by Swork91** [comment]
Cool thanks.
